import Link from "next/link";
import { getAdminBooks, getCuratedLists, queryBooks } from "@/lib/db";
import AdminBookForm from "./book-form";

export default async function AdminPage() {
  const books = await getAdminBooks();
  const lists = await getCuratedLists();
  const linkHealth = await queryBooks(`SELECT COUNT(*) AS total, SUM(CASE WHEN last_checked_at IS NULL OR last_checked_at < datetime('now','-30 day') THEN 1 ELSE 0 END) AS stale FROM book_links`);
  return <div className="container admin"><div className="eyebrow">Private CMS</div><h1>BooksHeaven Admin</h1><div className="notice">Protect <code>/admin</code> with Cloudflare Zero Trust Access. This project intentionally does not implement a second custom authentication system.</div><div className="admin-layout" style={{marginTop:22}}><aside className="admin-nav panel"><Link href="/admin">Dashboard</Link><a href="#books">Books</a><a href="#lists">Curated lists</a><Link href="/admin/lists">Manage lists →</Link><a href="#health">Link health</a></aside><div><section id="books" className="panel"><div className="section-head"><h2>Books & curation queue</h2><span className="muted">Sorted by views</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Book</th><th>Status</th><th>Views</th><th>Public domain</th><th>Action</th></tr></thead><tbody>{books.map((b)=><tr key={String(b.id)}><td>{String(b.title)}</td><td>{String(b.source)}</td><td>{String(b.view_count)}</td><td>{Number(b.public_domain)?"Yes":"No"}</td><td><Link className="btn secondary" href={`/admin/books/${b.id}`}>Edit</Link></td></tr>)}</tbody></table></div></section><section id="lists" className="panel section"><div className="section-head"><h2>Curated lists</h2></div><div className="list">{lists.map(l=><Link className="list-item" href={`/best/${l.slug}`} key={String(l.id)}><div><strong>{String(l.title)}</strong><div className="muted">/{String(l.slug)}</div></div><span>Preview →</span></Link>)}</div></section><section id="health" className="panel section"><h2>Link health</h2><p className="muted">{String(linkHealth[0]?.stale || 0)} of {String(linkHealth[0]?.total || 0)} links are missing a recent check or are older than 30 days.</p></section></div></div></div>
}
